### ISSUE TITLE
Системата не изпраща мейл за потвърждение

### ISSUE THREAD

**Issue by tabakoff** [initLab/fauna#100]
Здрасти! При регистриране на нов потребител, системата не изпраща мейл за потвърждение на регистрацията.  

Ако опитам да се регистрирам пак, системата изписва, че мейлът съществува в базата данни, така че все пак го пази някъде. 

Лека!

**Comment by ignisf** [comment]
Здрасти,

Мейл сървърът ти връща следното съобщение:

`host XXXXXXX.eu[XXX.XXX.XXX.XXX] said: 550 Access denied - Invalid HELO name (See RFC2821 4.1.1.1) (in reply to MAIL FROM command)`

**Comment by ignisf** [comment]
Можеш да поискаш наново мейл за потвърждение тук: https://fauna.initlab.org/users/confirmation/new

**Comment by ignisf** [comment]
Освен това мисля, че можеш да си използваш акаунта дори да не ти е потвърден мейла?

**Comment by tabakoff** [comment]
Преди да продължите, трябва да потвърдите регистрацията си - така че не ме пуска с непотвърден мейл.

Не става и с повторното потвърждение, просто не изпраща нищо,, исках няколко пъти.

ПП - проверил съм си спама :)

**Comment by krokodilerian** [comment]
Оправих пречещата настройка на mail server-а при нас, @tabakoff, пробвай пак.

**Comment by tabakoff** [comment]
готови сме! :) Мерси!
