### ISSUE TITLE
Не се инсталират зависимости на Ubuntu Xenial

### ISSUE THREAD

**Issue by zeridon** [initLab/fauna#101]
```
ubuntu@ubuntu-xenial:/vagrant$ ./bin/setup 
== Installing dependencies ==

[!] There was an error parsing `Gemfile`: `ruby_24` is not a valid platform. The available options are: [:ruby, :ruby_18, :ruby_19, :ruby_20, :ruby_21, :ruby_22, :ruby_23, :mri, :mri_18, :mri_19, :mri_20, :mri_21, :mri_22, :mri_23, :rbx, :jruby, :jruby_18, :jruby_19, :mswin, :mswin_18, :mswin_19, :mswin_20, :mswin_21, :mswin_22, :mswin_23, :mswin64, :mswin64_19, :mswin64_20, :mswin64_21, :mswin64_22, :mswin64_23, :mingw, :mingw_18, :mingw_19, :mingw_20, :mingw_21, :mingw_22, :mingw_23, :x64_mingw, :x64_mingw_20, :x64_mingw_21, :x64_mingw_22, :x64_mingw_23]. Bundler cannot continue.

 #  from /vagrant/Gemfile:56
 #  -------------------------------------------
 #  # Add Ruby 2.4.0 support
 >  gem 'xmlrpc', platforms: :ruby_24
 #  
 #  -------------------------------------------

```

**Comment by ignisf** [comment]
Стара версия на bundler......................................................................

**Comment by zeridon** [comment]
След `gem install bundle` и `bundle install` скрипта минава до някъде но пак изгърмява със същото след като попита за първи потребител.

```
ubuntu@ubuntu-xenial:/vagrant$ bundle --version
Bundler version 1.15.4
```

**Comment by int3l** [comment]
@zeridon при мен се наложи да добавя няколко неща върху чистия Xenial.

1. Стандартна инсталация: секцията за Ruby - [Setup Ruby on Ubuntu 16.04 Xenial Xerus](https://gorails.com/setup/ubuntu/16.04#ruby)

1. Инсталация на `libpq-dev` нужна за PostgreSQL джема (нужнен за production setup-a - той е по подразбиране).

1. Добавяне на `tzinfo-data` джема към останалите изисквания/зависимости (Gemfile-a).

Ползвам същата версия на Bundler-а като теб.
