### ISSUE TITLE
Започнаха редовно да остават във фауната хора, които вече не са в Лаба

### ISSUE THREAD

**Issue by vlood** [initLab/fauna#104]
Случай 1: Вени си бачка от вкъщи, аз гледам фауната - уж е там.

Случай 2: Вени идва на работа днес сутринта. Лаба е отключен, а вътре се водим аз и 3-ма мизери-лабърс. Това с отключеното може да е от друго, ще подпитам Ружи снощи дали заключи след мен. Обаче прожекторите отвън може да са светили цяла нощ заради предполагаемото ми присъствие, за което не знам.

**Comment by ignisf** [comment]
мяф

**Comment by user890104** [comment]
Светили са, защото е било отключено, а не защото е показвало че има хора в лаба.

Имам съмнения, че фауната не отчита хората правилно след като рестартирахме spitfire на 9.11.2017 около 22 ч.

**Comment by ignisf** [comment]
нищо чудно

**Comment by user890104** [comment]
Ако фауната се чупи при рестарт на машината, това би говорило зле за стабилността ѝ.

**Comment by ignisf** [comment]
епа фиксни я, или се научи да админстваш

**Comment by user890104** [comment]
Не тръгна автоматично даже, трябваше да пишем bundle install нещо-си, и после да изровим от крон-а командата за стартиране.

Имаш ли идея какъв може да е проблема с обновяването на потребителите (с какво може да е свързан, как да го оправим и т.н.) ?

**Comment by ignisf** [comment]
рестартирали сте радиус сървъра, без да рестартирате всичките аксес поинтове, които са имали активни сесии към него

**Comment by ignisf** [comment]
оправно.
