### ISSUE TITLE
Функционалността Забравена Парола не работи

### ISSUE THREAD

**Issue by batruji** [initLab/fauna#105]
Въвеждам `batruji@gmail.com` тук:
https://fauna.initlab.org/users/password/new
Сигурен съм, че мейлът ми е регистриран, но не си спомням паролата си и имам нужда от смяна. Не получавам мейл от системата. 
Дали може някой да ми я смени ръчно или да оправи мейл известията? Благодаря!

**Comment by alordiel** [comment]
@batruji  я пробвай пак, аз се цъкнах два пъти и с някакво закъснение дойдоха и двата мейла (освен ако някой не е сръчкал нещата междувременно).

**Comment by ignisf** [comment]
Би трябвало да е оправено
