### ISSUE TITLE
Проблем с разпознаване по мак адреса

### ISSUE THREAD

**Issue by alordiel** [initLab/fauna#108]
Имаме случай на нов потребител, който вкарва мака адреса си след регистрация във фауната и фауната продължава да го показва като мистериозен лабър. Акаунта е регистриран на postivan@protonmail.com

**Comment by ignisf** [comment]
Да не би да е посочил, че не желае да присъства в публични списъци?
![Screenshot 2019-03-25 at 18 09 00](https://user-images.githubusercontent.com/1153188/54935645-6055cd00-4f29-11e9-98cd-f591117d0c38.png)

**Comment by eehmo** [comment]
![Screenshot from 2019-03-25 20-17-15](https://user-images.githubusercontent.com/37116977/54936195-9e072580-4f2a-11e9-889b-03553b5bf75d.png)

**Comment by alordiel** [comment]
Точно туй беше посочил : ) Благодарим за светкавичната реакция.

**Comment by ignisf** [comment]
<img width="695" alt="Screenshot 2019-03-27 at 13 41 09" src="https://user-images.githubusercontent.com/1153188/55073312-0c1c2b80-5096-11e9-85dc-825e7a4535be.png">

**Comment by eehmo** [comment]
![Screenshot from 2019-03-27 17-45-24](https://user-images.githubusercontent.com/37116977/55080827-75586a80-50a7-11e9-9f19-d0e68d0d73a4.png)
