### ISSUE TITLE
По-малко плашещо съобщение в преводите

### ISSUE THREAD

**Issue by user890104** [initLab/fauna#109]
Получих фийдбек от нов член, че при регистрацията е избрал "Не искам да присъствам в публични списъци", защото звучи все едно разлепваме някъде списъци с всички наши членове години назад, или им водим някакво досие. Предлагам да се смени примерно на "Показвай присъствието ми в Лаба" (да се инвертира логиката на чекбокса, и по дефолт да е чекнат) защото обединява показването в presence и изписване на името при отваряне/отключване. Или да остане така, а текста да е "Не показвай кога съм в Лаба".
@initLab/council мнения?

**Comment by ignisf** [comment]
По-скоро, вместо да се чудите за гупости, предлагам да стане opt-in това. Искам да се вижда кога присъствам в лаба и всички да виждат името ми.

**Comment by ignisf** [comment]
и по подразбиране да не е чекнато

**Comment by user890104** [comment]
Ок тогава, щом искаш да го правим културно, нека да е с пояснение

[ ] Показвай присъствието ми в Лаба
Ако изберете тази отметка, Вашето име, потребителско име, аватар и публични данни от профила (сайт, гитхъб, туитър) ще са видими на началната страница на Fauna. Ако не я изберете, ще бъдете показван като Mystery labber.
[ ] Показвай името ми при отключване, заключване и отваране на входната врата
Ако изберете тази отметка, Вашето потребителско име ще бъде изпращано в Twitter, IRC и Telegram, когато отключвате, заключвате или отваряте входната врата. Ако не я изберете, действията пак ще се изпращат, но вместо с името Ви, ще пише Someone who does not wish to be named, unlocked/locked/opened the door.

**Comment by ignisf** [comment]
Повече от една отметка не искам да имплементирам. Или искаш да ти се вижда името от хора извън УС, или не.

**Comment by user890104** [comment]
Добре тогава, ето редактиран текст:

[ ] Показвай името ми когато съм в Лаба и когато отварям вратата
Ако изберете тази отметка, Вашето име, потребителско име, аватар и публични данни от профила (сайт, гитхъб, туитър) ще са видими на началната страница на Fauna. Вашето потребителско име ще бъде изпращано в Twitter, IRC и Telegram, когато отключвате, заключвате или отваряте входната врата.
Ако не я изберете, ще бъдете показван като Mystery labber, а действията Ви свързани с входната врата пак ще се изпращат, но вместо с името Ви, ще пише Someone who does not wish to be named, unlocked/locked/opened the door.

**Comment by user890104** [comment]
Оправих скриптовете в /usr/local/sbin/
