### ISSUE TITLE
Автоматично попълване на данни при регистрация

### ISSUE THREAD

**Issue by ignisf** [initLab/fauna#11]
* Автоматично добавяне на MAC адреса, от който потребителя се регистрира
* Автоматично попълване на twitter handle на базата на електронна поща

**Comment by zeridon** [comment]
При положение че има и гпг фингърпринт може би и опит за автоматично откриване на база мейл адрес.

**Comment by ignisf** [comment]
Не, изборът на GPG fingerprint трябва да бъде експлицитен

**Comment by ignisf** [comment]
излишно
