### ISSUE TITLE
Разширяване на door логиката

### ISSUE THREAD

**Issue by alex-milanov** [initLab/fauna#112]
**Цел:**
Да може да се отключва през нея студиото и офисното и да може лесно да се добавят нови врати, които да се управляват през нея

**Изисквания:**
- да може да се дефинират отделни entry-та (входна, студио, офис)
- да се разшири текущата loging и notification функционалност
- да се улесни връзката към хардуерната част

**Стъпки:**
- [x] Мапване на сетъпа на spitfire-a
- [x] Мапване на db schema-та и api-endpoint-ите
- [ ] door entity/model (app/models/{door.rb, door/})
- [ ] door actions (app/controllers/door/)
...

**ref:**
![fauna links schema](https://github.com/initLab/initLab/raw/master/doc/fauna_schema.png)
![fauna-sql-diagram](https://user-images.githubusercontent.com/1308365/62429050-32239d80-b712-11e9-8400-8271799387ec.png)
[fauna-api-schema-map-2019-08-04.zip](https://github.com/initLab/fauna/files/3465306/fauna-api-schema-map-2019-08-04.zip)

**Comment by alex-milanov** [comment]
Създадох това issue за да има малко структура в това което правим по fauna-та в момента. Добавил съм неща които сме свършили с цел да разберем как са навързани нещата и какви са endpoint-ите на текущия app/api. Следващите стъпки просто съм ги нахвърлил набързо. До колкото виждам в схемата таблиците просто логват действията и статуса на вратата.  Ще трябва да се добави нова таблица doors и текущите да линкват и към нея.
Ще работя по локалния сетъп от https://github.com/initLab/ecosystem

**Comment by ignisf** [comment]
Done?
