### ISSUE TITLE
Показване на наличие на хора дори и да не са регистрирани във Fauna

### ISSUE THREAD

**Issue by zeridon** [initLab/fauna#27]
Би било полезно да се показва че има някой в лаба дори и той да не е регистриран във фауната (примерно mystery man)

Вероятно ще е добре да е единична икона (а не за всеки).

**Comment by ignisf** [comment]
Agreed

**Comment by ignisf** [comment]
Блях... Дали presence системата няма да стане излишна.. даже нежелана, след като проимаме индикатор на състоянието на вратата?

**Comment by vlood** [comment]
Надали. Малко хора ще имат право да отключват вратата, а тези, които не могат, евентуално ще искат да знаят колко народ има в Лаба, щото ако има един самотен анонимен мушмул, надали ще искат да се засилят до Лаба, ако след половин час мушмулът може и да го няма.

**Comment by ignisf** [comment]
https://github.com/initLab/fauna/commit/ccb4723f3879944dab87ac5f2034358bb74c58fa
