### ISSUE TITLE
CORS правила за фауна

### ISSUE THREAD

**Issue by zeridon** [initLab/fauna#28]
В момента CORS правилата са широко отворени. Трябва да се затегнат малко

    Access-Control-Allow-Origin: *
    Access-Control-Request-Method: *

Информация: https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS

**Comment by ignisf** [comment]
Къде видя?

**Comment by zeridon** [comment]
On вт, 2015-03-03 at 00:14 -0800, Petko Bordjukov wrote:
> Къде видя?
> 
> —
> Reply to this email directly or view it on GitHub.
> 
> 

curl -k -v https://fauna.initlab.org -o /dev/null
-- 
Regards
Vladimir Vitkov

**Comment by ignisf** [comment]
https://github.com/initLab/fauna/blob/master/app/controllers/users_controller.rb#L2

**Comment by ignisf** [comment]
Така де, cors-а е permissive само за GET UsersController#present във връзка с тази функционалност https://github.com/initLab/initlanesis/issues/49

**Comment by zeridon** [comment]
Няма ли да е по логично да се ограничи само до initlab.org? Т.е. като цяло си е вътрешна система няма за какво с ajax разни хорица да могат да си го гледат.

**Comment by ignisf** [comment]
може ли да стане portable

**Comment by ignisf** [comment]
т.е. ако VarnaLab искат да използват фауна, да не трябва да пипат в сорса

**Comment by ignisf** [comment]
Пак съм недоспал.. то че може да се ограничи – може, но въпросът е как да не присъства стринга initlab в сорса и струва ли си :)

**Comment by zeridon** [comment]
On ср, 2015-03-04 at 04:13 -0800, Petko Bordjukov wrote:
> Пак съм недоспал.. то че може да се ограничи – може, но въпросът е как
> да не присъства стринга initlab в сорса и струва ли си :)
> 
> —
> Reply to this email directly or view it on GitHub.
> 
> 

Опция в конфиг файла? т.е. нещо от сорта на base_lab_url
-- 
Regards
Vladimir Vitkov
