### ISSUE TITLE
Затягане на сигурността около имейлите за смяна на парола

### ISSUE THREAD

**Issue by ignisf** [initLab/fauna#30]
@skanev изрази резерви към компромисите с UX-а на фауна и по-точно изтъкна, въвеждането на парола при промяна на лична информация е излишно, защото ако някой има достъп до лаптопа ти с логната сесия, вероятно има достъп и до мейла ти и съответно може да промени паролата.

Предлагам чрез email да могат да променят паролата си само хора, които са въвели fingerprint на GPG ключ и може да им бъде изпратен шифриран мейл, а всички останали да трябва да се свържат с член на УС. Представям си реакцията на  @skanev при предложението за такова осакатяване на UX-а, какво мислят останалите? @krokodilerian @batruji @vlood @isld?

**Comment by batruji** [comment]
Според мен е нормално да се иска парола при смяна на данни. Ако някой има достъп до лаптопа ти според мен не е нещо, от което си струва да се предпазваме (пазете си лаптопите!). Иначе в тоя ред на мисли ако някой ти е на лаптопа и криптирания мейл няма да помогне.

**Comment by vlood** [comment]
Промяна на телефон трябва да води до лишаване на правата на тоя телефон до отваряне на вратата, докато не бъде одобрен (маркиран?) от баш-администратор на системата. Баш-администратор на системата е някой като Петко или друг от УС, който умее да си заключва компа, когато не е на него.

Това е моето мнение, което не знам като имплементация колко ще е лесно.

**Comment by ignisf** [comment]
харесва ми @vlood как мисли

**Comment by ignisf** [comment]
за казаното от @vlood съм създал #69, другото отпада
