### ISSUE TITLE
Да се показва статуса на вратата

### ISSUE THREAD

**Issue by krokodilerian** [initLab/fauna#32]
На страницата на фауната да се показва дали вратата е отключена или не (има лесен начин да се пита doorpi-то).

**Comment by ignisf** [comment]
Обмислям как да стане. Трябва и https://github.com/kzyapkov/pesho/issues/1 да се вземе предвид

**Comment by krokodilerian** [comment]
Не е задължително, може просто да пускаш заявка до вратата и да даваш резултата, не е нужно да се консултираш с текущия си state.

**Comment by ignisf** [comment]
По принцип – да, притеснява ме, че всяка заявка към фауна, ще означава заявка към пешо.

**Comment by kzyapkov** [comment]
Pesho вече може да нотифицира с HTTP POST. Адреса се конфигурира в pesho.conf, ако е празен нотификациите са изключени.

По подразбиране не приема невалидни https сертификати, но вярвам, че не ви е проблем.

**Comment by ignisf** [comment]
@kzyapkov <3
