### ISSUE TITLE
Timeout на отключването (още малко security)

### ISSUE THREAD

**Issue by isld** [initLab/fauna#33]
Не знам дали няма вече такова нещо, но мисля че при отключване на вратата, тя трябва да се заключва отново ако не е отворена в някакъв времеви интервал, примерно минутка-две.

**Comment by vlood** [comment]
От друга страна ако батерията ми е на умирачка и тръгвам към Лаба, бих звъннал, преди да стигна, за да е отключено поне отдолу, че да мога да си отворя с ключа ръчната брава...

**Comment by ignisf** [comment]
Хм... @krokodilerian искаше да имплементираме журнал във фауната, който да показва промените в статуса на вратата, така че като отключиш, да можеш да провериш дали е отворено след това.

**Comment by ignisf** [comment]
Та предполагъм въпросът е, нужно ли ни е автоматично да се заключи сама вратата или е по-добре просто да можеш да провериш дали е отворена след като си отключил. Или да се праща мейл, ако не е отворена?

**Comment by krokodilerian** [comment]
Аз съм против всякаква такава логика, щото:
1) колкото по-сложно, толкова по-лесно ще се простреляме в крака;
2) аз мога да отключа на някакви хора 10-20 минути преди да идат;

@vlood , ако батерията е на умиране, вероятно в лаба няма ток така или иначе :)

Ако се пазим от това лабът да остане случайно отключен, можем да реализираме сравнително лесно check, който да проверява в 23:30 всеки ден дали е заключено и ако не, да пуска notification на няколко човека, по sms или нещо такова.

**Comment by vlood** [comment]
Батерията на телефона ми, крокодиле, не на бравата.

Ако телефонът ми е на умирачка, ще си остана отвън на студа. Ако пък мога да кажа на вратата да се отключи след 20 минути и да седи отключена 15 минути след това, би било прекрасно.

**Comment by ignisf** [comment]
Така е, основен недостатък на телефоните, за разлика от ключовете, е че са на батерия

**Comment by krokodilerian** [comment]
@vlood, ами освен да не забравяш да си зареждаш батерията или да изкараме един извод под звънеца за захранване ... :)

По-скоро трябва да измислим резервен вариант с клавиатура някаква отвън или нещо такова, което не иска ток, ако трябва да борим такива ситуации, което е за отделно issue.

**Comment by ignisf** [comment]
ХА, това с извеждането на microusb от вратата ми хареса!! :)) Но да, от начало още планът беше от самата врата да си се отваря с RFID (и нещо другу), това е друга тема.

**Comment by ignisf** [comment]
Хората са масово против тази функционалност, ако изобщо има още желаещи да се имплементира, моля отворете наново и обяснете защо е нужно.
