### ISSUE TITLE
Смяна на паролата не работи?

### ISSUE THREAD

**Issue by batruji** [initLab/fauna#35]
https://fauna.initlab.org/users/password

Поради някаква причина не можах да влезна във фауната със старта си парола и реших да я сменя. Каквато и нова парола да въведа ми изкарва, че има грешка във формата.

![screenshot-fauna initlab org 2015-03-17 15-26-17](https://cloud.githubusercontent.com/assets/846646/6688193/29c3cb70-ccba-11e4-97f1-a3c121b0bc5e.png)

**Comment by alordiel** [comment]
Сигурен ли си че те активиран акаунта. Пробвай с двата линка отдолу за отключване и потвърждаване.  Имах същия проблем и се оказа, че трябва първо да си потвърдиш акаунта.

**Comment by batruji** [comment]
Пробвах с линковете - потвърдих си мейла, но пак излиза същото. Реално валидацията работи ОК, когато паролата е по-малко от 8 символа или има несъответствие м/у двете пароли. Когато въведа валидна парола обаче, ми се показва екран със съобщение за грешка, но без показана конкретна такава. Пробвах на Chrome и Firefox

**Comment by ignisf** [comment]
данке, това е интересен edge case, когато не ти е активиран акаунта :(. Не съм имал време да го дебъгвам още, успя ли все пак да се логнеш?

**Comment by ignisf** [comment]
Добрееем, ето какво става.

По някое време @3ightbit въведе използване на username за логин. В момента username-а е задължително поле.

Оказва се, че когато потребител няма въведено потребителско име и опита да смени паролата си, Rails връща грешка заради липсващото потребителско име.

Как да излезем от тази ситуация? Мисля си да въведа за потребителско име на всички, които нямат, първата част на email-а им? Как мислите?

**Comment by batruji** [comment]
Звучи добре, ако така се разреши проблема, то звучи логично като подход

**Comment by ignisf** [comment]
готово
