### ISSUE TITLE
Mobile-friendly версия

### ISSUE THREAD

**Issue by user890104** [initLab/fauna#42]
Здравейте! Ето как изглежда фауната от мрежова гледна точка:
![fauna](https://cloud.githubusercontent.com/assets/3518994/9021414/8d0b5202-3849-11e5-99f8-2cfa2993f5db.png)
Сега си представете как някой чака пред вратата минута и половина, защото тези 718 kB се зареждат за толкова на мобилно устройство, ако скоростта на връзката му е средно 8 kB/s (или 45 секунди ако е на 16).
Възможно ли е да се направи супер-lightweight версия (не повече от 10-20 kB общо), и да се сервира само на мобилни устройства?
Наясно съм, че веднъж след като тези файлове се заредят, браузъра ги кешира, но от гледна точка на UX е ужасно да чакаш минута за шрифт или грид, при положение че щом го отваряш на мобилно у-во, търсиш функционалност.

**Comment by SharedInitlab** [comment]
Принципно си прав. Но нещо не е наред, ако не успяваш да се вържеш на
мрежата на Лаба, когато си пред вратата :Р

Vladimir Vassilev
root @ init Lab
+359 885 448475
http://initlab.org

2015-08-01 12:40 GMT+03:00 Vencislav Atanasov <notifications@github.com>:

**Comment by user890104** [comment]
Бях с ново устройство, в което не беше записана парола. Въпроса ми е по-скоро дали това е възможно да се осъществи (т.е. има ли начин да се направи custom версия на bootstrap), или трябва да ставаме модерни и да ползваме винаги бърз нет.

**Comment by ignisf** [comment]
![mx2z1mh](https://cloud.githubusercontent.com/assets/1153188/9021652/29063ee4-3857-11e5-98cc-6afa69671641.png)

1. https://github.com/initLab/fauna/commit/1bc6a155e969b7d8f20870ad51b7b457416faab4
2. Активиране на gzip компресия на всичко в `/assets`. Там данните са статични и очаквам да няма импликации от гледна точка на сигурност.

Какво още може да се направи:

  * Граватарите да се кешират локално при първа регистрация и след това потребителите да си качват снимки. Това нямам време да го правя.
  * Да се напише мобилно приложение, което да ползва JSON API-то на Fauna.

Какво няма да направя – няма да правя специална версия за мобилни клиенти. Цялата идея на използването на bootstrap и правенето на responsive неща, е да няма специална версия за мобилни клиенти.

**Comment by user890104** [comment]
Супер, изглежда в пъти по-добре :)

**Comment by user890104** [comment]
счупило се е мобилното меню

**Comment by ignisf** [comment]
fixed

**Comment by ignisf** [comment]
От nineties мрежата в лаба:
![9rekvzi](https://cloud.githubusercontent.com/assets/1153188/9060332/5970e7da-3abb-11e5-86f9-ef070e142dfc.png)
