### ISSUE TITLE
Регистрацията може би не работи при липса на хора в Лаба?!

### ISSUE THREAD

**Issue by vlood** [initLab/fauna#48]
Момците организиращи Друпал срещата са мъчили да се регистрират и не станало. Днес са ок.

**Comment by ignisf** [comment]
Уат? :) какво им е казало? Имало ли е грешка?

**Comment by vlood** [comment]
Не помнят, това е било март месец когато си правеха събитието в Лаба.

On Wed, Apr 27, 2016 at 7:13 PM, Petko Bordjukov <notifications@github.com>
wrote:

> Уат? :) какво им е казало? Имало ли е грешка?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/initLab/fauna/issues/48#issuecomment-215134891>
>



-- 
** Simplicity*
  More time for enjoying life, less for emailing.
  Please, adopt the Email Charter - emailcharter.org

**Comment by ignisf** [comment]
Не би следвало да има връзка, ако се появи отново този проблем, веднага да кажете, за да го дебъгвам.
