### ISSUE TITLE
Да се извеждат ролите на присъстващите в лаба лабъри

### ISSUE THREAD

**Issue by ignisf** [initLab/fauna#86]
- [ ] да се изведе сценарий/сценарии за употребата на тази функционалност
- [ ] да се анализират възможните начини, по който могат да бъдат адресирани сценариите и да се избере оптимален от тях

**Comment by zeridon** [comment]
Ehm ... NO. Звучи като наистина лоша идея.

**Comment by Dragast** [comment]
@zeridon Аргументация нещо?

**Comment by zeridon** [comment]
Публична видимост кой кой е (и за какъв достъп/права/етц може да го експлойтваш и гониш).

Основен принцип в системите които предоставят/контролират някаква информация е да предоставят/разкриват минимално необходимата такава. Извеждането на ролята на *всеки* видим върви против това.

Ако ще се изписват роли то тогава нека са обобщени за популацията в момента (УС в сградата, има кой да отвори етц). Имайки предвид че тя обикновенно не е много голяма по-добре изобщо да няма такава функционалност.

**Comment by user890104** [comment]
Към момента, и двете неща са публично видими:
УС: https://github.com/orgs/initLab/teams/council
Членове: https://docs.google.com/spreadsheets/d/1j2TPgKBd8CsAwnPJLoGECuBNPRXvXGtZuf-RS34WVvY/edit#gid=14 (таб Приходи)

Предлагам да е под формата на лентички (диагонална 45° горе вляво) върху аватара на потребителя, в страницата с присъстващи, и в тях да пише УС или Член.
От техническа гледна точка, май в момента няма роля "Член", а само УС, Доверен член и Потребител. Тук вече става въпрос за интеграция на фауната с членския внос, но ако се добави четвърта роля, не мисля че ще е много трудно да се обновяват ръчно всеки месец примерно.
